spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/cloudDB01
  application:
    name: microservicecloud-provider-dept

mapper:
  mappers: com.baidu.mapper
  identity: mysql
  not-empty: false

logging:
  level:
     com.offcn.springcloud.mapper : debug
eureka:
  client:
    service-url:
      defaultZone : http://localhost:7001/eureka
  instance:
      instance-id: microservicecloud-dept8081
      prefer-ip-address: true
server:
  port: 8081




